# Project information
site_name: Beike's blog.
site_url: https://beike-zh.github.io/
site_author: beike-zh

# Repository
repo_name: beike-zh/beike-zh.github.io
repo_url: https://github.com/beike-zh/beike-zh.github.io
edit_uri: ''

# Copyright
copyright: beike-zh

theme:
  name: material
  palette:
    - scheme: default
      primary: black 
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
# formatting
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols

# toc
  - toc:
      permalink: true  
# highlight line-number
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline  
  - pymdownx.inlinehilite
  - pymdownx.superfences
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# LaTeX 
  - pymdownx.arithmatex:
      generic: true


plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true
      lang:
        - en


# LaTeX 
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js