site_name: Beike's blog.
repo_name: beike-zh/beike-zh.github.io
repo_url: https://github.com/beike-zh/beike-zh.github.io
edit_uri: ''

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
# Because i didn't use the insiders  version
#    - scheme: slate
#      primary: indigo
#      accent: blue
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode


markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
# formatting
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols

# toc
  - toc:
      permalink: true  
# highlight line-number
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline  
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# LaTeX 
  - pymdownx.arithmatex:
      generic: true


plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true
      lang:
        - en